AWSTemplateFormatVersion: 2010-09-09
Description: Stack for DynamoDBs and other persistence layer

Parameters:
  SolutionName:
    Type: String

Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "email"
          AttributeType: "S"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: "email"
          KeyType: "HASH"
      SSESpecification:
        SSEType: KMS
        SSEEnabled: true
      TableName: !Sub ${SolutionName}-users

  LoginRequestsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "email"
          AttributeType: "S"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: "email"
          KeyType: "HASH"
      SSESpecification:
        SSEType: KMS
        SSEEnabled: true
      TableName: !Sub ${SolutionName}-login-requests
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true

Outputs:
  UsersTable:
    Description: User dynamodb table name
    Value: !Ref UsersTable
  UsersTableArn:
    Description: User dynamodb table arn
    Value: !GetAtt UsersTable.Arn
  LoginRequestsTable:
    Description: Login requests table name
    Value: !Ref LoginRequestsTable
  LoginRequestsTableArn:
    Description: Login requests table arn
    Value: !GetAtt LoginRequestsTable.Arn